#!/bin/bash
#
# Usage: curl https://raw.githubusercontent.com/MartinPavelka/DO-vulnApp-DO/main/run | bash
#
#
index_main() {
    set -e
    curl -s -S -L https://raw.githubusercontent.com/MartinPavelka/DO-vulnApp-DO/main/script.sh | bash
}
